# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: "DockerHubConnection"
        repository: "ir0nsidee/terraformbase"
        command: "buildAndPush"
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: Terraform
  displayName: Provisioning with Terraform
  dependsOn: Build
  jobs:
    - job: Provision
      displayName: "Provisioning Container Instance"
      pool: 
        vmImage: ubuntu-latest
      variables:
        - group: TerraformBaseServicePrincipleLib
      steps:
        - script: |
            set -e
            cd $(Build.SourcesDirectory)/deploy
            terraform init -input=false
            terraform apply -input=false -auto-approve
          name: "Terraform"
          displayName: "Run Terraform Script"
          env:
            ARM_CLIENT_ID: $(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
            ARM_TENANT_ID: $(ARM_TENANT_ID)
            ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
            TF_VAR_IMAGE_BUILD_TAG: $(tag)