version: "3"
services:
  postgreserver:
    image: docker.io/postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "P4ssw0rd!"
      POSTGRES_DB: "GraphQLDB"
    ports:
      - "5432:5432"
    expose:
      - 5432