#platform-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformapi
  template:
    metadata:
      labels:
        app: platformapi
    spec:
      containers:
        - name: platformapi
          image: ir0nsidee/platformapi:latest
---
#platform-clusterip
apiVersion: v1
kind: Service
metadata:
  name: platform-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platformapi
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80    
--- 
#platform-mssql-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-mssql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-mssql
  template:
    metadata:
      labels:
        app: platform-mssql
    spec:
      containers:
        - name: platform-mssql
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_PID
              value: "Express"
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: platform-mssql
                  key: SA_PASSWORD
          volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: mssqldb
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: platform-mssql-claim
---
#platform-mssql-clusterip
apiVersion: v1
kind: Service
metadata:
  name: platform-mssql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: platform-mssql
  ports:
  - name : platform-mssql
    protocol: TCP
    port: 1433
    targetPort: 1433 
---
#optional loadbalancer to access platform mssql from desktop
apiVersion: v1
kind: Service
metadata:
  name: platform-mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: platform-mssql
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433